Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.box_check_update = true
    config.vm.boot_timeout = 10000

    # enable gui and set memory to 2048Mb
    config.vm.provider "virtualbox" do |v|
      v.gui = true
      v.memory = 2048
    end
    config.vm.provision :shell, path: "skripta.sh"
  end