Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.box_check_update = true
    config.vm.boot_timeout = 10000

    # enable gui and set memory to 2048Mb
    config.vm.provider "virtualbox" do |v|
      v.gui = true
      v.memory = 2048
    end
    config.vm.provision :shell, path: "skripta.sh"

      # Permit anyone to start the GUI
  config.vm.provision "shell", inline: "sudo sed -i 's/allowed_users=.*$/allowed_users=anybody/' /etc/X11/Xwrapper.config"
  end